function obj = BUOYmatrix(obj)

obj.MassMatrix = [obj.windTurbine.Mass obj.windTurbine.Mass*obj.windTurbine.CenterOfMass 0 0; ...
  obj.windTurbine.Mass*obj.windTurbine.CenterOfMass obj.windTurbine.Inertia0 0 0; ...
  0 0 obj.windTurbine.Mass obj.windTurbine.Mass*obj.windTurbine.CenterOfMass; ...
  0 0 obj.windTurbine.Mass*obj.windTurbine.CenterOfMass obj.windTurbine.Inertia0];
%Check for Cm  =1 and after i see how to do it]
Cm = 1;
obj.AddedMassMatrix = [-obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*obj.windTurbine.floater.draft -(1/2)*obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*(obj.windTurbine.floater.draft)^2 0 0; ...
    -(1/2)*obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*(obj.windTurbine.floater.draft)^2 -(1/3)*obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*(obj.windTurbine.floater.draft)^3 0 0; ...
    0 0 -obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*obj.windTurbine.floater.draft -(1/2)*obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*(obj.windTurbine.floater.draft)^2; ...
    0 0 -(1/2)*obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*(obj.windTurbine.floater.draft)^2 -(1/3)*obj.WaveSimulation.Density*(pi)*(((2*obj.windTurbine.floater.Radius)^2)/4)*Cm*(obj.windTurbine.floater.draft)^3];
if obj.KmoorAutoCalculate == 1
    T_mooring = 100;
    HydroStatic = [0 0 0 0;0 obj.windTurbine.Mass*obj.WaveSimulation.Gravity*((1/2)*obj.windTurbine.floater.draft-obj.windTurbine.CenterOfMass)+obj.WaveSimulation.Density*obj.WaveSimulation.Gravity*((1/4)*(obj.windTurbine.floater.Radius^4)*pi) 0 0;0 0 0 0;0 0 0 obj.windTurbine.Mass*obj.WaveSimulation.Gravity*((1/2)*obj.windTurbine.floater.draft-obj.windTurbine.CenterOfMass)+obj.WaveSimulation.Density*obj.WaveSimulation.Gravity*((1/4)*(obj.windTurbine.floater.Radius^4)*pi)];
    obj.Cmatrix = (4*pi^2)*((obj.MassMatrix+obj.AddedMassMatrix)/T_mooring)+HydroStatic;
else
    obj.Cmatrix=[obj.windTurbine.floater.Kmoor obj.windTurbine.floater.Kmoor*obj.windTurbine.floater.Zmoor 0 0; ...
    obj.windTurbine.floater.Kmoor*obj.windTurbine.floater.Zmoor obj.windTurbine.floater.Kmoor*obj.windTurbine.floater.Zmoor^2+obj.windTurbine.Mass*obj.WaveSimulation.Gravity*((1/2)*obj.windTurbine.floater.draft-obj.windTurbine.CenterOfMass)+obj.WaveSimulation.Density*obj.WaveSimulation.Gravity*((1/4)*(obj.windTurbine.floater.Radius^4)*pi) 0 0; ...
    0 0 obj.windTurbine.floater.Kmoor obj.windTurbine.floater.Kmoor*obj.windTurbine.floater.Zmoor; ...
    0 0 obj.windTurbine.floater.Kmoor*obj.windTurbine.floater.Zmoor obj.windTurbine.floater.Kmoor*obj.windTurbine.floater.Zmoor^2+obj.windTurbine.Mass*obj.WaveSimulation.Gravity*((1/2)*obj.windTurbine.floater.draft-obj.windTurbine.CenterOfMass)+obj.WaveSimulation.Density*obj.WaveSimulation.Gravity*((1/4)*(obj.windTurbine.floater.Radius^4)*pi)];
end