function obj = PlotAllChecker(obj)
figure
subplot(3,3,1)
mesh(rad2deg(obj.AngleOfAttackTotal))
title('Angle of attack')
subplot(3,3,2)
mesh(obj.localRelativeVelocityTotal)
title('local relative velocity')
subplot(3,3,3)
mesh(obj.CnTotal)
title('Cn')
subplot(3,3,4)
mesh(obj.CtTotal)
title('Ct')
subplot(3,3,5)
mesh(obj.V1)
title('V1')
subplot(3,3,6)
mesh(obj.V2)
title('V2')
subplot(3,3,7)
mesh([obj.localReynoldNumberUp obj.localReynoldNumberDown])
title('local Reynolds Number Upwind')
subplot(3,3,8)
mesh([obj.ClUp' obj.ClDown'])
title('Cl')
subplot(3,3,9)
mesh([obj.CdUp' obj.CdDown'])
title('Cd')
figure;
subplot(2,1,1)
mesh([obj.FinalInterferenceFactorUpwind obj.FinalInterferenceFactorDownwind])
title('Interference Factor')
subplot(2,1,2)
mesh([obj.localTSRUp obj.localTSRDown])
title('local Tip Speed Ratio')